name: nhl
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_1000
  - asn1crypto=0.24.0=py37_1003
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37hccf1714_0
  - click=7.0=py_0
  - colorama=0.4.1=py_0
  - cryptography=2.6.1=py37h212c5bf_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py37_1002
  - icu=58.2=hfc679d8_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h24bf2e0_1001
  - ipython=7.1.1=py37h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.1=py37_1000
  - jinja2=2.10=py_1
  - jpeg=9c=h470a237_1
  - jsonschema=3.0.0a3=py37_1000
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.6=py37_0
  - jupyterlab_server=0.2.0=py_0
  - libcxx=8.0.0=2
  - libcxxabi=8.0.0=2
  - libffi=3.2.1=hfc679d8_5
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.35=ha92aebf_2
  - libsodium=1.0.16=h470a237_1
  - markupsafe=1.1.0=py37h470a237_0
  - mistune=0.8.4=py37h470a237_0
  - mkl=2018.0.3=1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - neobolt=1.7.13=py37h01d97ff_0
  - neotime=1.7.4=py_0
  - notebook=5.7.2=py37_1000
  - numpy=1.11.3=py37heee0a97_5
  - openssl=1.1.1b=h01d97ff_2
  - pandas=0.23.4=py37hf8a1672_0
  - pandoc=2.3.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pexpect=4.6.0=py37_1000
  - pickleshare=0.7.5=py37_1000
  - pip=18.1=py37_1000
  - prometheus_client=0.4.2=py_0
  - prompt_toolkit=2.0.7=py_0
  - ptyprocess=0.6.0=py37_1000
  - py2neo=4.2.0=py_1
  - pycparser=2.19=py37_1
  - pygments=2.4.0=py_0
  - pymongo=3.7.2=py37h0a44026_0
  - pyopenssl=19.0.0=py37_0
  - pyqt=5.6.0=py37h8210e8a_7
  - pyrsistent=0.14.6=py37h470a237_0
  - pysocks=1.7.0=py37_0
  - python=3.7.1=haf84260_7
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - pyzmq=17.1.2=py37hae99301_1
  - qt=5.6.2=h4e759b2_10
  - qtconsole=4.4.3=py_0
  - readline=7.0=haf1bffa_1
  - send2trash=1.5.0=py_0
  - setuptools=40.6.2=py37_0
  - sip=4.18.1=py37hfc679d8_0
  - six=1.11.0=py37_1001
  - sqlite=3.25.3=hb1c47c0_0
  - terminado=0.8.1=py37_1001
  - testpath=0.4.2=py37_1000
  - tk=8.6.9=ha92aebf_0
  - tornado=5.1.1=py37h470a237_0
  - traitlets=4.3.2=py37_1000
  - wcwidth=0.1.7=py_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_1000
  - xz=5.2.4=h470a237_1
  - zeromq=4.2.5=hfc679d8_6
  - zlib=1.2.11=h470a237_3
  - pip:
    - alabaster==0.7.12
    - atomicwrites==1.2.1
    - babel==2.6.0
    - beautifulsoup4==4.6.3
    - bleach==3.0.2
    - chardet==3.0.4
    - docutils==0.14
    - hockey-scraper==1.32.4
    - html5lib==1.0.1
    - idna==2.7
    - imagesize==1.1.0
    - lxml==4.2.5
    - more-itertools==4.3.0
    - neo4j==1.7.3
    - packaging==18.0
    - pluggy==0.8.0
    - py==1.7.0
    - pyparsing==2.3.0
    - pytest==4.0.0
    - requests==2.20.1
    - snowballstemmer==1.2.1
    - sphinx==1.8.2
    - sphinxcontrib-websupport==1.1.0
    - urllib3==1.24.1
    - webencodings==0.5.1
prefix: /Users/btibert/anaconda3/envs/nhl

