name: nhl
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1b=h1de35cc_1
  - pip=19.1.1=py37_0
  - python=3.7.3=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - alabaster==0.7.12
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - babel==2.6.0
    - beautifulsoup4==4.7.1
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - docutils==0.14
    - hockey-scraper==1.32.4
    - html5lib==1.0.1
    - idna==2.8
    - imagesize==1.1.0
    - jinja2==2.10.1
    - lxml==4.3.3
    - markupsafe==1.1.1
    - more-itertools==7.0.0
    - neobolt==1.7.13
    - neotime==1.7.4
    - numpy==1.16.3
    - packaging==19.0
    - pandas==0.24.2
    - pluggy==0.11.0
    - prompt-toolkit==2.0.9
    - py==1.8.0
    - py2neo==4.3.0
    - pygments==2.3.1
    - pyparsing==2.4.0
    - pytest==4.5.0
    - python-dateutil==2.8.0
    - pytz==2019.1
    - requests==2.21.0
    - six==1.12.0
    - snowballstemmer==1.2.1
    - soupsieve==1.9.1
    - sphinx==2.0.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - urllib3==1.24.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
prefix: /Users/btibert/miniconda3/envs/nhl

